version: "3.9"
services:
  db:
    build: .
    container_name: postgis_db
    restart: unless-stopped
    env_file: .env
    ports:
      - "${PG_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
      - ./seed:/seed:ro

  adminer:
    image: adminer:latest
    container_name: adminer_ui
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "${ADMINER_PORT}:8080"
    environment:
      ADMINER_DEFAULT_SERVER: db

volumes:
  pgdata:
